# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to ~/.config/fish/completions/modbus_scanner_rpc.fish
# 2) Ensure a binary named modbus_scanner_rpc is in your PATH
# See also: https://fishshell.com/docs/current/completions.html#where-to-put-completions


# Parse current commandline:
# - _shtab_modbus_scanner_rpc_cmdpath=(sub)command path seen so far
# - _shtab_modbus_scanner_rpc_npos=number of positional arguments given after it
# - options are skipped based on _shtab_modbus_scanner_rpc_opts_with_value & _shtab_modbus_scanner_rpc_commands lists
function _shtab_modbus_scanner_rpc_scan
  set -g _shtab_modbus_scanner_rpc_cmdpath ''
  set -g _shtab_modbus_scanner_rpc_npos 0
  set -l tokens (commandline -opc)
  set -e tokens[1]
  set -l expect_value 0
  for t in $tokens
    if test $expect_value -eq 1
      set expect_value 0
      continue
    end
    switch "$t"
      case '--*=*'
        continue
      case '-*'
        if contains -- $t $_shtab_modbus_scanner_rpc_opts_with_value
          set expect_value 1
        end
        continue
      case '*'
        if test $_shtab_modbus_scanner_rpc_npos -eq 0
          set -l candidate $t
          if test -n "$_shtab_modbus_scanner_rpc_cmdpath"
            set candidate "$_shtab_modbus_scanner_rpc_cmdpath $t"
          end
          if contains -- $candidate $_shtab_modbus_scanner_rpc_commands
            set -g _shtab_modbus_scanner_rpc_cmdpath $candidate
            continue
          end
        end
        set -g _shtab_modbus_scanner_rpc_npos (math $_shtab_modbus_scanner_rpc_npos + 1)
    end
  end
end

# Condition helper: true if the current (sub)command path equals the given one.
function _shtab_modbus_scanner_rpc_using
  _shtab_modbus_scanner_rpc_scan
  test "$_shtab_modbus_scanner_rpc_cmdpath" = "$argv"
end

set -g _shtab_modbus_scanner_rpc_commands 
set -g _shtab_modbus_scanner_rpc_opts_with_value --broker --response-timeout -o

complete -c modbus_scanner_rpc -e
complete -c modbus_scanner_rpc -f

complete -c modbus_scanner_rpc -n _shtab_modbus_scanner_rpc_using -s h -l help -d 'show this help message and exit'
complete -c modbus_scanner_rpc -n _shtab_modbus_scanner_rpc_using -l debug -d 'Enable debug output (default: False)'
complete -c modbus_scanner_rpc -n _shtab_modbus_scanner_rpc_using -l broker -x -d 'Mqtt broker url (default: unix:///var/run/mosquitto/mosquitto.sock)'
complete -c modbus_scanner_rpc -n _shtab_modbus_scanner_rpc_using -s o -x -d 'Timeout, ms (default: 10000)'
complete -c modbus_scanner_rpc -n _shtab_modbus_scanner_rpc_using -l response-timeout -x -d 'Response timeout, ms (passed to wb-mqtt-serial RPC) (default: None)'

